version: "3.8"
name: uat-econtract-server-container
services:
  nodejs:
    build: ./
    image: uat-econtract-nodejs-server:1.0
    container_name: uat-econtract-nodejs-container
    restart: always
    volumes:
      - "./econtract-container-volumes/storage:/usr/src/app/storage"
    ports:
      - 1312:1312
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
    environment:
      NODE_ENV: production
      JWT_SECRET: 2c1f6f154f3ec3098a2084416567614c623231aa1560f3d5c4420d704bb222d5
      DB_HOST: 159.228.251.212
      DB_PASSWORD: "D@!cel009"
